Repository neo4j-devtools/relate, pull requests merged in 2020-10, with the labels that each got.

#198 Fix graphql-upload stream not complete
  packages/common/src/system/system.provider.ts
  packages/web/src/entities/project/graphql-upload.ts
  packages/web/src/entities/project/project.resolver.ts
Labels: bug

#204 Bugfix config reset upgrade
  packages/cli/src/modules/dbms/upgrade.module.ts
  packages/common/src/entities/dbmss/dbmss.local.ts
  packages/common/src/entities/dbmss/upgrade.test.ts
  packages/common/src/entities/environments/environment.constants.ts
  packages/common/src/utils/dbmss/dbms-upgrade-config.ts
  scripts/tests/setup.js
Labels: bug, enhancement

#29 Relate Extensions RFC
  documentation/EVENT_HOOKS.md
  documentation/EXTENSIONS.md
  documentation/RFCs/relate-extensions/relate-extensions.rfc.md
Labels: documentation, help wanted

#218 Feature public extensions
  package.json
  packages/cli/docs/extension.md
  packages/cli/src/commands/extension/install.ts
  packages/cli/src/modules/extension/install.module.ts
  packages/cli/src/modules/extension/list.module.ts
  packages/cli/src/modules/extension/uninstall.module.ts
  packages/common/package-lock.json
  packages/common/package.json
  packages/common/src/constants.ts
  packages/common/src/entities/dbmss/dbmss.local.ts
  packages/common/src/entities/environments/environment.constants.ts
  packages/common/src/entities/extensions/extensions.abstract.ts
  packages/common/src/entities/extensions/extensions.constants.ts
  packages/common/src/entities/extensions/extensions.local.ts
  packages/common/src/entities/extensions/extensions.remote.ts
  packages/common/src/index.ts
  packages/common/src/models/extension.model.ts
  packages/common/src/utils/extensions/download-extension.ts
  packages/common/src/utils/extensions/extension-versions.test.ts
  packages/common/src/utils/extensions/extension-versions.ts
  packages/common/src/utils/extensions/extract-extension.ts
  packages/common/src/utils/extensions/get-app-base-path.ts
  packages/common/src/utils/extensions/get-app-base-paths.test.ts
  packages/common/src/utils/extensions/get-installed-extensions.ts
  packages/common/src/utils/extensions/load-extensions-for.ts
  packages/common/src/utils/system/test-extensions.ts
Labels: enhancement, good first issue

#223 Feature remote STATIC extensions
  package.json
  packages/cli/src/modules/app/app.e2e.ts
  packages/cli/src/modules/app/open.module.ts
  packages/client/src/utils.ts
  packages/common/src/constants.ts
  packages/common/src/entities/extensions/extensions.local.ts
  packages/common/src/index.ts
  packages/common/src/utils/extensions/get-app-base-path.ts
  packages/common/src/utils/extensions/get-app-launch-url.ts
  packages/common/src/utils/extensions/index.ts
  packages/common/src/utils/generic/is-valid-url.ts
  packages/electron/src/window/window.module.ts
  packages/web/src/entities/extension/extension.constants.ts
  packages/web/src/entities/extension/extension.e2e.ts
  packages/web/src/entities/extension/extension.resolver.ts
  packages/web/src/entities/extension/extension.types.ts
  packages/web/src/entities/extension/extension.utils.ts
Labels: enhancement, good first issue

#219 common/extensions install and web/extensions.e2e tests
  packages/common/src/entities/extensions/extensions.local.ts
  packages/common/src/entities/extensions/install.test.ts
  packages/common/src/utils/extensions/extension-versions.test.ts
  packages/common/src/utils/system/test-extensions.ts
  packages/web/src/entities/extension/extension.e2e.ts
  packages/web/src/entities/extension/extension.resolver.ts
Labels: Chore

#226 Chore separate access token files
  .eslintrc.json
  packages/cli/src/modules/db/load.module.ts
  packages/cli/src/modules/environment/init.module.ts
  packages/cli/src/prompts/select.prompt.ts
  packages/common/src/constants.ts
  packages/common/src/entities/dbmss/dbmss.local.ts
  packages/common/src/entities/environments/environment.abstract.ts
  packages/common/src/system/system.provider.ts
  packages/common/src/utils/dbmss/cypher-shell.ts
  packages/common/src/utils/system-access-token.ts
  packages/common/src/utils/system/test-dbmss.ts
  packages/web/src/auth/services/auth.service.ts
Labels: Chore
